#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_FULL_PATH=${SCRIPT_DIR}/$(basename ${BASH_SOURCE[0]})
POWERSHELL="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
trap ctrlC INT

tmp=`mktemp`


verifyExecutablePresent() {
    local cmd=$1
    if which $1 ; then
        echo Prechecks: $1 present
    else
        echo Prechecks: install $1, please.
        exit 1;
    fi 
} 


removeTempFiles() {
    rm -f $tmp
}

ctrlC() {
    echo
    echo "Trapped Ctrl-C, removing temporary files"
    removeTempFiles
    stty sane
}


verifyExecutablePresent netmask
verifyExecutablePresent ${POWERSHELL}


echo "Creating new resolv.conf"
echo "------------------------"
{
    echo "# Generated by ${SCRIPT_FULL_PATH}"
    echo "# add the following two lines to /etc/wsl.conf to keep wsl from overwriting it"
    echo "#   [network]"
    echo "#   generateResolvConf = false"
    echo
    echo "# Window's ipv4 DNS servers in interface priority"

    # get interfaces IPv4 addresses in increasing interface metric priority
    nameservers=$(${POWERSHELL} -Command "Get-DnsClientServerAddress -AddressFamily ipv4  -InterfaceIndex  (Get-NetIpInterface -AddressFamily IPV4 | sort-object InterfaceMetric).ifIndex | Select-Object -ExpandProperty ServerAddresses")
    for i in $nameservers; do
        echo nameserver $i
    done
    echo

    # always add the WSL virtual adapter gateway
    echo "# WSL vEthernet gateway"
    wslGateway=$(netmask $(ip addr show dev eth0 | grep "inet "| sed -e 's: *inet ::' | sed -e 's: .*::') | tr -d ' ' | sed -e 's:\.0/.*:.1:')
    echo nameserver=${wslGateway}

} | tr -d '\r' | tee $tmp

echo
set +e
(set -x; diff --ignore-trailing-space $tmp /etc/resolv.conf)
DE=$?
set -e
if [ $DE == 0 ] ; then
    echo Unchanged
else
     (set -x; sudo cp $tmp /etc/resolv.conf)
     echo Updated
fi

removeTempFiles
