#!/usr/bin/env bash
set -euo pipefail


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_FULL_PATH=${SCRIPT_DIR}/$(basename ${BASH_SOURCE[0]})
COMMAND_DIR=$( cd -- "$( dirname -- "${0}" )" &> /dev/null && pwd )
COMMAND_FULL_PATH=${COMMAND_DIR}/$(basename ${0})
POWERSHELL="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"

. ${SCRIPT_DIR}/common.sh
verifyExecutablePresent ip
verifyExecutablePresent ipcalc
verifyExecutablePresent ${POWERSHELL}
echo >&5

tmp=`mktemp`

removeTempFiles() {
    rm -f $tmp
}

ctrlC() {
    echo
    echo "Trapped Ctrl-C, removing temporary files"
    removeTempFiles
    stty sane
}

trap ctrlC INT

echo >&5 "Creating new resolv.conf"
echo >&5 "--------------------------------"
{
    echo "# Generated by ${SCRIPT_FULL_PATH} (run via ${COMMAND_FULL_PATH})"
    echo "# add the following two lines to /etc/wsl.conf to keep wsl from overwriting it"
    echo "#"
    echo "#   [network]"
    echo "#   generateResolvConf = false"
    echo
    echo "# Windows' ipv4 DNS servers in interface priority"

    # get interfaces IPv4 addresses in increasing interface metric priority
    nameservers=$(${POWERSHELL} -Command "Get-DnsClientServerAddress -AddressFamily ipv4  -InterfaceIndex  (Get-NetIpInterface -AddressFamily IPV4 | sort-object InterfaceMetric).ifIndex | Select-Object -ExpandProperty ServerAddresses")
    for i in $nameservers; do
        echo nameserver $i
    done
    echo

    # always add the WSL virtual adapter gateway
    echo "# WSL vEthernet gateway"
    default_if=$(ip route list | awk '/^default/ {print $5}')
    default_if_cidr_addr=$(ip -o -f inet addr show $default_if | awk '{print $4}')
    wslGateway=$(ipcalc "$default_if_cidr_addr" | awk '/HostMin/ {print $2}')
    echo nameserver=${wslGateway}
} | tr -d '\r' | tee $tmp >&5
echo >&5 "--------------------------------"
echo >&5

chmod a+r "$tmp"
syncFile "$tmp" "/etc/resolv.conf"
removeTempFiles
